# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "840e9101eff951d30a606acad694c1c6"
name = "hello-marchant-app"
handle = "hello-marchant-app"
application_url = "https://experiences-cry-kinda-history.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "lumin-app-test.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://experiences-cry-kinda-history.trycloudflare.com/auth/callback",
  "https://experiences-cry-kinda-history.trycloudflare.com/auth/shopify/callback",
  "https://experiences-cry-kinda-history.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
